---
- name: Issue certificate(s)
  hosts: localhost
  become: false
  gather_facts: false
  vars_files:
    - "{{ playbook_dir }}/roles/admin-vault-deploy/defaults/main.yml"
    - "{{ playbook_dir }}/secrets/vault.yml"
  vars:
    cert_chain_file: "{{ playbook_dir }}/secrets/certs/dev-chain.pem"
    cert_key_file: "{{ playbook_dir }}/secrets/certs/dev-key.pem"
  tasks:
    - name: Stat {{ cert_chain_file }}
      stat:
        path: "{{ cert_chain_file }}"
      register: cert_file

    - name: Check if existing cert is about to expire
      openssl_certificate:
        path: "{{ cert_chain_file }}"
        provider: assertonly
        valid_in: 2592000 # 30 days
      ignore_errors: True
      register: validity_check
      when: cert_file.stat.exists == true

    - name: Issue and save new certificate
      block:
        - name: Issue new certificate
          include_tasks: "{{ playbook_dir }}/roles/admin-vault-deploy/tasks/issue.yml"
          vars:
            dns_domain: "{{ dev_apps_domain }}"
            hashi_vault_url: https://omni-dev-vault-vault-02.aws.omnitracs.com:8200/
          with_items:
            - "{{ app_name }}-proxy-{{ dev_namespace }}"

        - name: Write cert_chain PEM file
          copy:
            content: "{{ secret_out.json.data.certificate }}\n{{ secret_out.json.data.ca_chain | join('\n') }}"
            dest: "{{ cert_chain_file }}"

        - name: Write cert_key PEM file
          copy:
            content: "{{ secret_out.json.data.private_key }}"
            dest: "{{ cert_key_file }}"

        - name: Encrypt private key
          shell: ansible-vault encrypt {{ cert_key_file }}
      when: (cert_file.stat.exists == false) or (validity_check is failed)

- name: Apply secrets
  hosts: secrets
  vars:
    cert_key: "{{ lookup('file', '{{ playbook_dir }}/secrets/certs/dev-key.pem') }}"
    cert_chain: "{{ lookup('file', '{{ playbook_dir }}/secrets/certs/dev-chain.pem') }}"
  tasks:
    - include_vars: "{{ playbook_dir }}/secrets/db-info-dev.yml"
    - include_role:
        name: openshift-applier/roles/openshift-applier
