---
deploy:
  dev:
    postgresclient:
      SECRET_NAME: "{{ app_name }}-dbcreds"
      USERNAME: "{{ database_user | b64encode }}"
      PASSWORD: "{{ database_password | b64encode }}"
    postgresadminclient:
      SECRET_NAME: "{{ app_name }}-admindbcreds"
      USERNAME: "{{ database_admin_user | b64encode }}"
      PASSWORD: "{{ database_admin_password | b64encode }}"
    certs:
      SECRET_NAME: "{{ app_name }}-proxy-certs"
      KEY: "{{ cert_key | b64encode }}"
      CHAIN: "{{ cert_chain | b64encode }}"
  test:
    postgresclient:
      SECRET_NAME: "{{ app_name }}-dbcreds"
      USERNAME: "{{ database_user | b64encode }}"
      PASSWORD: "{{ database_password | b64encode }}"
    postgresadminclient:
      SECRET_NAME: "{{ app_name }}-admindbcreds"
      USERNAME: "{{ database_admin_user | b64encode }}"
      PASSWORD: "{{ database_admin_password | b64encode }}"
    certs:
      SECRET_NAME: "{{ app_name }}-proxy-certs"
      KEY: "{{ cert_key | b64encode }}"
      CHAIN: "{{ cert_chain | b64encode }}"
openshift_cluster_content:
- object: secrets-deploy 
  content:
  - name: "{{ app_name }}-{{ dev.NAMESPACE }}-dbcreds"
    template: "https://bitbucket.org/omnitracslab/openshift-templates/raw/{{ openshift_templates_ver }}/secrets/secret-user-pass-template.yml"
    params_from_vars: "{{ deploy.dev.postgresclient }}"
    namespace: "{{ dev.NAMESPACE }}"
    tags:
    - secrets
    - db
  - name: "{{ app_name }}-{{ dev.NAMESPACE }}-admindbcreds"
    template: "https://bitbucket.org/omnitracslab/openshift-templates/raw/{{ openshift_templates_ver }}/secrets/secret-user-pass-template.yml"
    params_from_vars: "{{ deploy.dev.postgresadminclient }}"
    namespace: "{{ dev.NAMESPACE }}"
    tags:
    - secrets
    - db
- object: proxy-certs-deploy
  content:
  - name: "{{ app_name }}-{{ dev.NAMESPACE }}-proxy-certs"
    template: "https://bitbucket.org/omnitracslab/openshift-templates/raw/{{ openshift_templates_ver }}/secrets/secret-cert-template.yml"
    params_from_vars: "{{ deploy.dev.certs }}"
    namespace: "{{ dev.NAMESPACE }}"
    tags:
    - secrets
    - certs
- object: test-secrets-deploy 
  content:
  - name: "{{ app_name }}-{{ test.NAMESPACE }}-dbcreds"
    template: "https://bitbucket.org/omnitracslab/openshift-templates/raw/{{ openshift_templates_ver }}/secrets/secret-user-pass-template.yml"
    params_from_vars: "{{ deploy.test.postgresclient }}"
    namespace: "{{ test.NAMESPACE }}"
    tags:
    - secrets
    - db
  - name: "{{ app_name }}-{{ test.NAMESPACE }}-admindbcreds"
    template: "https://bitbucket.org/omnitracslab/openshift-templates/raw/{{ openshift_templates_ver }}/secrets/secret-user-pass-template.yml"
    params_from_vars: "{{ deploy.test.postgresadminclient }}"
    namespace: "{{ test.NAMESPACE }}"
    tags:
    - secrets
    - db
- object: test-proxy-certs-deploy
  content:
  - name: "{{ app_name }}-{{ test.NAMESPACE }}-proxy-certs"
    template: "https://bitbucket.org/omnitracslab/openshift-templates/raw/{{ openshift_templates_ver }}/secrets/secret-cert-template.yml"
    params_from_vars: "{{ deploy.test.certs }}"
    namespace: "{{ test.NAMESPACE }}"
    tags:
    - secrets
    - certs
